#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry 'Slackware Linux 4.4 Frankenboot' --class gnu-linux --class gnu --class os $menuentry_id_option 'osprober-gnulinux-simple-5b66b7bc-2271-4c17-aceb-ce67b6871d2a' {
	insmod part_msdos 
	insmod ext2
	set root='hd0,msdos1'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos1 --hint-efi=hd0,msdos1 --hint-baremetal=ahci0,msdos1  5b66b7bc-2271-4c17-aceb-ce67b6871d2a
	else
	  search --no-floppy --fs-uuid --set=root 5b66b7bc-2271-4c17-aceb-ce67b6871d2a
	fi
	linux /boot/vmlinuz-generic-4.4 root=UUID=5b66b7bc-2271-4c17-aceb-ce67b6871d2a ro
	initrd /boot/initrd-4.4.gz
}
